### ISSUE TITLE
For autocrystal

### ISSUE THREAD

**Issue by notperry1** [CreepyOrb924/creepy-salhack#1]
**Is your feature request related to a problem? Please describe.**
Make it instead of ticks make it two different options placespeed and attackspeed cause ticks you cant customize the attack or place speed so having ticks at 1 makes crystals place fast as heck but then the attack speeds so high that ncp makes it so you cant hit it and its so annoying if you make place speed and attackspeed the autocrystal would be 10x better cause if you up the ticks it will start to work but then the crystal placement is so slow

**Describe the solution you'd like**
idk

**Describe alternatives you've considered**
idk

**Additional context**
just harder to pvp when you cant hit crystals

**Comment by yagel15637** [comment]
@CreepyOrb924 i might send a pr featuring this soon

**Comment by CreepyOrb924** [comment]
One thing I have been experimenting with is stealing the wurst+2 ca (since it is really good). The results so far are looking promising but fps spike bugs are giving me a headache so I do not know when it might be fully functional.

**Comment by yagel15637** [comment]
w+2 ca is ok but massively flawed, and it's bad practice to depend on other's code

**Comment by CreepyOrb924** [comment]
Fair enough, I will experiment with fixing the current SalHack ca too.
