### ISSUE TITLE
Error when running ./gradlew runClient

### ISSUE THREAD

**Issue by h0rb** [CreepyOrb924/creepy-salhack#10]
Hello, 
I am trying to build and run this project but i get some errors. I am using intelliJ idea to run this project
here is the error output. 
Edit: i ran ./gradlew clean , ./gradlew setupDecompworkspace and ./gradlew genIntellijRuns first 
https://paste.ubuntu.com/p/hPWKCjp4fd/

**Comment by CreepyOrb924** [comment]
I can not recreate your error, so I don't know how to help you.
