### ISSUE TITLE
Game crashes when I open the console

### ISSUE THREAD

**Issue by Pirobit** [CreepyOrb924/creepy-salhack#25]
When I click the console module or click the up arrow, the game crashes almost instantly

**Comment by CreepyOrb924** [comment]
![Give Crash Report](https://user-images.githubusercontent.com/41650640/106202285-af08c980-6187-11eb-8cf6-0922a5790e55.gif)

**Comment by Pirobit** [comment]
[crash-2021-01-29_17.54.13-client.txt](https://github.com/CreepyOrb924/creepy-salhack/files/5896763/crash-2021-01-29_17.54.13-client.txt)

**Comment by CreepyOrb924** [comment]
Try deleting your SalHack folder in .minecraft.
