### ISSUE TITLE
Modules don't work

### ISSUE THREAD

**Issue by Troodon04563** [CreepyOrb924/creepy-salhack#26]
Except for freecam, no modules work for me. I tried re-installing everything a few times and it still doesn't fix. I'm using multimc.
It happens in both singleplayer and multiplayer.
![2021-01-28_16 17 01](https://user-images.githubusercontent.com/35642955/106189093-977d1100-6186-11eb-9b21-850a49838aaf.png)
![2021-01-28_16 18 54](https://user-images.githubusercontent.com/35642955/106189097-98ae3e00-6186-11eb-979c-4ac4d6770ed4.png)

**Comment by CreepyOrb924** [comment]
Deleting SalHack in your .minecraft folder and running it with the regular launcher. I need more information to solve this.

**Comment by Troodon04563** [comment]
Ok so I tried running it with the official launcher and it works. 
Here I'll give you some information about the instance where I tried to run Salhack. I don't know if I'm missing some key info, pardon my ignorance
[https://paste.ee/p/fQQwx](url)
I'm using Forge 14.23.5.2854 with Optifine 1.12.2 HD U G5. The only mod I'm loading is Salhack
