### ISSUE TITLE
ArrayList disappearing

### ISSUE THREAD

**Issue by Lqnz** [CreepyOrb924/creepy-salhack#29]
**To Reproduce**
1. Go to 'HUDEditor'
2. Turn on ArrayList and right click it
3. And it will disappeared

**Expected behavior**
Well I was trying to move the ArrayList but it will disappear. I tried to turn GUI Scale into Small in Video Settings to see if the ArrayList is still there but it's none.
I tried turning off and on the ArrayList thing but nothing works. Deleting the SalHack folder and reinstalling the client has no effect so please fix this annoying bug?

**Comment by CreepyOrb924** [comment]
If deleting your SalHack folder doesn't help I do no know what will.

**Comment by Leps15** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'HUDEditor'
> 2. Turn on ArrayList and right click it
> 3. And it will disappeared
> 
> **Expected behavior**
> Well I was trying to move the ArrayList but it will disappear. I tried to turn GUI Scale into Small in Video Settings to see if the ArrayList is still there but it's none.
> I tried turning off and on the ArrayList thing but nothing works. Deleting the SalHack folder and reinstalling the client has no effect so please fix this annoying bug?

it seems that the arraylist goes from corner to corner and when u right clicked for me it went out of my screen so for example my max Position Y of monitor is "466.0" it went over it to Position Y "855.2"

**Comment by CreepyOrb924** [comment]
I will close it at that.
