### ISSUE TITLE
ArrayList wont work

### ISSUE THREAD

**Issue by TheLordGoose8008** [CreepyOrb924/creepy-salhack#53]
When i tried moving ArrayList from the right side of my screen to the left it bugged out and wont show up anymore unless i click reset on it which allows it to show up for a split second before leaving again

**Comment by dunyakhin** [comment]
Hi, can I see xml code for this activity? U can move ListView on your screen, not ArrayList. ArrayList is a dynamic massive that u can show by ListView..in general I think u r using wrong type of layout and ListView just hiding. Drop xml code here

**Comment by TheLordGoose8008** [comment]
i will when i use it next time
